### ISSUE TITLE
검색기능 

### ISSUE THREAD

**Issue by amicitia2019** [amicitia2019/kakaomomesafe#1]
BoardDAO  --469

**Comment by amicitia2019** [comment]
[board.zip](https://github.com/amicitia2019/kakaomomesafe/files/6914374/board.zip)

**Comment by dcuIntelligentWeb** [comment]
select title from t_board WHERE title LIKE '%' || '8월' || '%' order by id;

**Comment by dcuIntelligentWeb** [comment]
select title from t_board  WHERE title  LIKE '%  8월 %' order by id

**Comment by dcuIntelligentWeb** [comment]
select title from t_board  WHERE title  LIKE '%8월%' order by id
